name: 'Draft release'

on:
  workflow_dispatch:
    inputs:
      version_strategy:
        description: 'Version strategy: The strategy to used to update the version based on semantic versioning (more info at https://semver.org/).'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  draft-release:
    uses: 'google-github-actions/.github/.github/workflows/draft-release.yml@29c6d38eeb974133b4b66401985f7c70cf4a6681' # v3
    permissions:
      contents: 'read'
      pull-requests: 'write'
    with:
      version_strategy: '${{ github.event.inputs.version_strategy }}'
    secrets:
      ACTIONS_BOT_TOKEN: '${{ secrets.ACTIONS_BOT_TOKEN }}'
